name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_emscripten:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@v11
    - name: build examples
      run: |
        rustup target add wasm32-unknown-emscripten
        cargo build --target=wasm32-unknown-emscripten
  build_others:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: build examples
      run: cargo build